version: "3.9"
services:
  tvheadend:
    container_name: tvheadend
    image: lscr.io/linuxserver/tvheadend:latest
    restart: unless-stopped # Do not change this
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
    volumes:
      - ${APP_DATA_DIR}/data/config:/config # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
      - ${ROOT_FOLDER_HOST}/media/data/recordings:/recordings
    ports:
      - ${APP_PORT}:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri
    networks:
      - tipi_main_network # That should not be changed
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.tvheadend-web-redirect.redirectscheme.scheme: https
      traefik.http.services.tvheadend.loadbalancer.server.port: 9981 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.tvheadend-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.tvheadend-insecure.entrypoints: web
      traefik.http.routers.tvheadend-insecure.service: tvheadend
      traefik.http.routers.tvheadend-insecure.middlewares: tvheadend-web-redirect
      # Websecure
      traefik.http.routers.tvheadend.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.tvheadend.entrypoints: websecure
      traefik.http.routers.tvheadend.service: tvheadend
      traefik.http.routers.tvheadend.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.tvheadend-local-insecure.rule: Host(`tvheadend.${LOCAL_DOMAIN}`)
      traefik.http.routers.tvheadend-local-insecure.entrypoints: web
      traefik.http.routers.tvheadend-local-insecure.service: tvheadend
      traefik.http.routers.tvheadend-local-insecure.middlewares: tvheadend-web-redirect
      # Local domain secure
      traefik.http.routers.tvheadend-local.rule: Host(`tvheadend.${LOCAL_DOMAIN}`)
      traefik.http.routers.tvheadend-local.entrypoints: websecure
      traefik.http.routers.tvheadend-local.service: tvheadend
      traefik.http.routers.tvheadend-local.tls: true