version: "3.7"
services:
  sonarr4k:
    image: lscr.io/linuxserver/sonarr:4.0.10
    container_name: sonarr4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    dns:
      - ${DNS_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media:/media
    ports:
      - ${APP_PORT}:8989
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.sonarr4k-web-redirect.redirectscheme.scheme: https
      traefik.http.services.sonarr4k.loadbalancer.server.port: 8989
      # Web
      traefik.http.routers.sonarr4k-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sonarr4k-insecure.entrypoints: web
      traefik.http.routers.sonarr4k-insecure.service: sonarr4k
      traefik.http.routers.sonarr4k-insecure.middlewares: sonarr4k-web-redirect
      # Websecure
      traefik.http.routers.sonarr4k.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sonarr4k.entrypoints: websecure
      traefik.http.routers.sonarr4k.service: sonarr4k
      traefik.http.routers.sonarr4k.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.sonarr4k-local-insecure.rule: Host(`sonarr4k.${LOCAL_DOMAIN}`)
      traefik.http.routers.sonarr4k-local-insecure.entrypoints: web
      traefik.http.routers.sonarr4k-local-insecure.service: sonarr4k
      traefik.http.routers.sonarr4k-local-insecure.middlewares: sonarr4k-web-redirect
      # Local domain secure
      traefik.http.routers.sonarr4k-local.rule: Host(`sonarr4k.${LOCAL_DOMAIN}`)
      traefik.http.routers.sonarr4k-local.entrypoints: websecure
      traefik.http.routers.sonarr4k-local.service: sonarr4k
      traefik.http.routers.sonarr4k-local.tls: true
      runtipi.managed: true
