version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
    - /postgres-data:/var/lib/postgresql/data # Mounting the volume
    networks:
      - tipi_main_network
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3000:3000" #Server Port
    volumes:
      - /backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.jellystat-web-redirect.redirectscheme.scheme: https
      traefik.http.services.jellystat.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.jellystat-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.jellystat-insecure.entrypoints: web
      traefik.http.routers.jellystat-insecure.service: jellystat
      traefik.http.routers.jellystat-insecure.middlewares: jellystat-web-redirect
      # Websecure
      traefik.http.routers.jellystat.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.jellystat.entrypoints: websecure
      traefik.http.routers.jellystat.service: jellystat
      traefik.http.routers.jellystat.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.jellystat-local-insecure.rule: Host(`jellystat.${LOCAL_DOMAIN}`)
      traefik.http.routers.jellystat-local-insecure.entrypoints: web
      traefik.http.routers.jellystat-local-insecure.service: jellystat
      traefik.http.routers.jellystat-local-insecure.middlewares: jellystat-web-redirect
      # Local domain secure
      traefik.http.routers.jellystat-local.rule: Host(`jellystat.${LOCAL_DOMAIN}`)
      traefik.http.routers.jellystat-local.entrypoints: websecure
      traefik.http.routers.jellystat-local.service: jellystat
      traefik.http.routers.jellystat-local.tls: true
      runtipi.managed: true
